/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clue.Dialog;

import clue.GameEngine.CardManager;
import clue.GameEngine.SuggestedInformation;
import clue.GamePieces.Card;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author glender
 */
public class SuggestionDialog extends javax.swing.JFrame {

	/**
	 * Creates new form SuggestionDialog
	 */
	public SuggestionDialog() {
		initComponents();
		
		// killers
		buttonGroup1.add(scarletBtn);
		buttonGroup1.add(mrGreenBtn);
		buttonGroup1.add(mrsWhiteBtn);
		buttonGroup1.add(mrsPeacockBtn);
		buttonGroup1.add(colMustardBtn);
		buttonGroup1.add(profPlumBtn);
		
		// weapon
		buttonGroup2.add(knifeBtn);
		buttonGroup2.add(ropeBtn);
		buttonGroup2.add(candleBtn);
		buttonGroup2.add(revolverBtn);
		buttonGroup2.add(pipeBtn);
		buttonGroup2.add(wrenchBtn);
		
		// room
		buttonGroup3.add(kitchenBtn);
		buttonGroup3.add(conservatoryBtn);
		buttonGroup3.add(ballroomBtn);
		buttonGroup3.add(hallBtn);
		buttonGroup3.add(billiardBtn);
		buttonGroup3.add(studyBtn);
		buttonGroup3.add(loungeBtn);
		buttonGroup3.add(libraryBtn);
		buttonGroup3.add(diningBtn);
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        scarletBtn = new javax.swing.JRadioButton();
        mrGreenBtn = new javax.swing.JRadioButton();
        mrsWhiteBtn = new javax.swing.JRadioButton();
        mrsPeacockBtn = new javax.swing.JRadioButton();
        colMustardBtn = new javax.swing.JRadioButton();
        profPlumBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        revolverBtn = new javax.swing.JRadioButton();
        ropeBtn = new javax.swing.JRadioButton();
        candleBtn = new javax.swing.JRadioButton();
        knifeBtn = new javax.swing.JRadioButton();
        wrenchBtn = new javax.swing.JRadioButton();
        pipeBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        ballroomBtn = new javax.swing.JRadioButton();
        billiardBtn = new javax.swing.JRadioButton();
        kitchenBtn = new javax.swing.JRadioButton();
        conservatoryBtn = new javax.swing.JRadioButton();
        hallBtn = new javax.swing.JRadioButton();
        libraryBtn = new javax.swing.JRadioButton();
        studyBtn = new javax.swing.JRadioButton();
        loungeBtn = new javax.swing.JRadioButton();
        diningBtn = new javax.swing.JRadioButton();
        makeSuggestionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scarletBtn.setText("Miss Scarlet");
        scarletBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scarletBtnActionPerformed(evt);
            }
        });

        mrGreenBtn.setText("Mr. Green");
        mrGreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrGreenBtnActionPerformed(evt);
            }
        });

        mrsWhiteBtn.setText("Mrs. White");
        mrsWhiteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrsWhiteBtnActionPerformed(evt);
            }
        });

        mrsPeacockBtn.setText("Mrs. Peacock");
        mrsPeacockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrsPeacockBtnActionPerformed(evt);
            }
        });

        colMustardBtn.setText("Col. Mustard");
        colMustardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colMustardBtnActionPerformed(evt);
            }
        });

        profPlumBtn.setText("Prof Plum");
        profPlumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profPlumBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Killer");

        jLabel2.setText("Weapon");

        revolverBtn.setText("Revolver");
        revolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revolverBtnActionPerformed(evt);
            }
        });

        ropeBtn.setText("Rope");
        ropeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ropeBtnActionPerformed(evt);
            }
        });

        candleBtn.setText("Candle Stick");
        candleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candleBtnActionPerformed(evt);
            }
        });

        knifeBtn.setText("Knife");
        knifeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knifeBtnActionPerformed(evt);
            }
        });

        wrenchBtn.setText("Wrench");
        wrenchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrenchBtnActionPerformed(evt);
            }
        });

        pipeBtn.setText("Pipe");
        pipeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Room");

        ballroomBtn.setText("Ballroom");
        ballroomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballroomBtnActionPerformed(evt);
            }
        });

        billiardBtn.setText("Billiard");
        billiardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billiardBtnActionPerformed(evt);
            }
        });

        kitchenBtn.setText("Kitchen");
        kitchenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenBtnActionPerformed(evt);
            }
        });

        conservatoryBtn.setText("Conservatory");
        conservatoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conservatoryBtnActionPerformed(evt);
            }
        });

        hallBtn.setText("Hall");
        hallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallBtnActionPerformed(evt);
            }
        });

        libraryBtn.setText("Library");
        libraryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryBtnActionPerformed(evt);
            }
        });

        studyBtn.setText("Study");
        studyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyBtnActionPerformed(evt);
            }
        });

        loungeBtn.setText("Lounge");
        loungeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loungeBtnActionPerformed(evt);
            }
        });

        diningBtn.setText("Dining Room");
        diningBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diningBtnActionPerformed(evt);
            }
        });

        makeSuggestionBtn.setText("Make Suggestion");
        makeSuggestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeSuggestionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scarletBtn)
                    .addComponent(mrGreenBtn)
                    .addComponent(mrsWhiteBtn)
                    .addComponent(mrsPeacockBtn)
                    .addComponent(colMustardBtn)
                    .addComponent(profPlumBtn))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(revolverBtn)
                    .addComponent(ropeBtn)
                    .addComponent(candleBtn)
                    .addComponent(knifeBtn)
                    .addComponent(wrenchBtn)
                    .addComponent(pipeBtn))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diningBtn)
                    .addComponent(loungeBtn)
                    .addComponent(studyBtn)
                    .addComponent(libraryBtn)
                    .addComponent(hallBtn)
                    .addComponent(conservatoryBtn)
                    .addComponent(kitchenBtn)
                    .addComponent(billiardBtn)
                    .addComponent(ballroomBtn)
                    .addComponent(jLabel3))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(makeSuggestionBtn))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {colMustardBtn, mrGreenBtn, mrsPeacockBtn, mrsWhiteBtn, profPlumBtn, scarletBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scarletBtn)
                    .addComponent(revolverBtn)
                    .addComponent(ballroomBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrGreenBtn)
                    .addComponent(ropeBtn)
                    .addComponent(billiardBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrsWhiteBtn)
                    .addComponent(candleBtn)
                    .addComponent(kitchenBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrsPeacockBtn)
                    .addComponent(knifeBtn)
                    .addComponent(conservatoryBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colMustardBtn)
                    .addComponent(wrenchBtn)
                    .addComponent(hallBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profPlumBtn)
                    .addComponent(pipeBtn)
                    .addComponent(libraryBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studyBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loungeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diningBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(makeSuggestionBtn))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {colMustardBtn, mrGreenBtn, mrsPeacockBtn, mrsWhiteBtn, profPlumBtn, scarletBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ropeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ropeBtnActionPerformed
        buttonGroup2.setSelected(ropeBtn.getModel(), true);
    }//GEN-LAST:event_ropeBtnActionPerformed

    private void revolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revolverBtnActionPerformed
        buttonGroup2.setSelected(revolverBtn.getModel(), true);
    }//GEN-LAST:event_revolverBtnActionPerformed

    private void scarletBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scarletBtnActionPerformed
        buttonGroup1.setSelected(scarletBtn.getModel(), true);
    }//GEN-LAST:event_scarletBtnActionPerformed

    private void mrGreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrGreenBtnActionPerformed
        buttonGroup1.setSelected(mrGreenBtn.getModel(), true);
    }//GEN-LAST:event_mrGreenBtnActionPerformed

    private void mrsWhiteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrsWhiteBtnActionPerformed
        buttonGroup1.setSelected(mrsWhiteBtn.getModel(), true);
    }//GEN-LAST:event_mrsWhiteBtnActionPerformed

    private void mrsPeacockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrsPeacockBtnActionPerformed
        buttonGroup1.setSelected(mrsPeacockBtn.getModel(), true);
    }//GEN-LAST:event_mrsPeacockBtnActionPerformed

    private void colMustardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colMustardBtnActionPerformed
        buttonGroup1.setSelected(colMustardBtn.getModel(), true);
    }//GEN-LAST:event_colMustardBtnActionPerformed

    private void profPlumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profPlumBtnActionPerformed
        buttonGroup1.setSelected(profPlumBtn.getModel(), true);
    }//GEN-LAST:event_profPlumBtnActionPerformed

    private void candleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candleBtnActionPerformed
        buttonGroup2.setSelected(candleBtn.getModel(), true);
    }//GEN-LAST:event_candleBtnActionPerformed

    private void knifeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knifeBtnActionPerformed
        buttonGroup2.setSelected(knifeBtn.getModel(), true);
    }//GEN-LAST:event_knifeBtnActionPerformed

    private void wrenchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrenchBtnActionPerformed
        buttonGroup2.setSelected(wrenchBtn.getModel(), true);
    }//GEN-LAST:event_wrenchBtnActionPerformed

    private void pipeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeBtnActionPerformed
        buttonGroup2.setSelected(pipeBtn.getModel(), true);
    }//GEN-LAST:event_pipeBtnActionPerformed

    private void ballroomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballroomBtnActionPerformed
        buttonGroup3.setSelected(ballroomBtn.getModel(), true);
    }//GEN-LAST:event_ballroomBtnActionPerformed

    private void billiardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billiardBtnActionPerformed
        buttonGroup3.setSelected(billiardBtn.getModel(), true);
    }//GEN-LAST:event_billiardBtnActionPerformed

    private void kitchenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenBtnActionPerformed
        buttonGroup3.setSelected(kitchenBtn.getModel(), true);
    }//GEN-LAST:event_kitchenBtnActionPerformed

    private void conservatoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conservatoryBtnActionPerformed
        buttonGroup3.setSelected(conservatoryBtn.getModel(), true);
    }//GEN-LAST:event_conservatoryBtnActionPerformed

    private void hallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallBtnActionPerformed
        buttonGroup3.setSelected(hallBtn.getModel(), true);
    }//GEN-LAST:event_hallBtnActionPerformed

    private void libraryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryBtnActionPerformed
        buttonGroup3.setSelected(libraryBtn.getModel(), true);
    }//GEN-LAST:event_libraryBtnActionPerformed

    private void studyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyBtnActionPerformed
        buttonGroup3.setSelected(studyBtn.getModel(), true);
    }//GEN-LAST:event_studyBtnActionPerformed

    private void loungeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loungeBtnActionPerformed
        buttonGroup3.setSelected(loungeBtn.getModel(), true);
    }//GEN-LAST:event_loungeBtnActionPerformed

    private void diningBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diningBtnActionPerformed
        buttonGroup3.setSelected(diningBtn.getModel(), true);
    }//GEN-LAST:event_diningBtnActionPerformed

    private void makeSuggestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeSuggestionBtnActionPerformed
        Card card = new Card();
		
		ButtonModel selection = buttonGroup1.getSelection();
		
		if (selection == scarletBtn.getModel()) {
			card = Card.scarlet;
		} else if (selection == mrGreenBtn.getModel()) {
			card = Card.green;
		} else if (selection == mrsWhiteBtn.getModel()) {
			card = Card.white;
		} else if (selection == mrsPeacockBtn.getModel()) {
			card = Card.peacock;
		} else if (selection == profPlumBtn.getModel()) {
			card = Card.plum;
		} else if (selection == colMustardBtn.getModel()) {
			card = Card.mustard;
		}

		SuggestedInformation.getInstance().killer = card.getCard(card.desc);
		
		selection = buttonGroup2.getSelection();
		
		if (selection == ropeBtn.getModel()) {
			card = Card.rope;
		} else if (selection == revolverBtn.getModel()) {
			card = Card.revolver;
		} else if (selection == candleBtn.getModel()) {
			card = Card.candle;
		} else if (selection == knifeBtn.getModel()) {
			card = Card.knife;
		} else if (selection == pipeBtn.getModel()) {
			card = Card.pipe;
		} else if (selection == wrenchBtn.getModel()) {
			card = Card.wrench;
		}
		
		SuggestedInformation.getInstance().weapon = card.getCard(card.desc);
		
		selection = buttonGroup3.getSelection();
		
		if (selection == ballroomBtn.getModel()) {
			card = Card.ballroom;
		} else if (selection == billiardBtn.getModel()) {
			card = Card.billiard;
		} else if (selection == conservatoryBtn.getModel()) {
			card = Card.conservatory;
		} else if (selection == studyBtn.getModel()) {
			card = Card.study;
		} else if (selection == loungeBtn.getModel()) {
			card = Card.lounge;
		} else if (selection == libraryBtn.getModel()) {
			card = Card.library;
		} else if (selection == hallBtn.getModel()) {
			card = Card.hall;
		} else if (selection == kitchenBtn.getModel()) {
			card = Card.kitchen;
		} else if (selection == diningBtn.getModel()) {
			card = Card.dining;
		}
		
		SuggestedInformation.getInstance().room = card.getCard(card.desc);
		
		System.out.println("LENDER -- solution chosen is " + SuggestedInformation.getInstance().room.desc + " " + SuggestedInformation.getInstance().killer + " " + SuggestedInformation.getInstance().weapon);
		
		this.setVisible(false);
		
		if (CardManager.getInstance().getKiller() == SuggestedInformation.getInstance().killer
			&& CardManager.getInstance().getWeapon() == SuggestedInformation.getInstance().weapon
			&& CardManager.getInstance().getRoom() == SuggestedInformation.getInstance().room) {
			
			JOptionPane.showMessageDialog(null,
								"Congratulations! You won the game!");
			SuggestedInformation.getInstance().win = true;
		} else {
			JOptionPane.showMessageDialog(null,
								"Sorry, you're wrong!");
			SuggestedInformation.getInstance().win = false;
		}
		
    }//GEN-LAST:event_makeSuggestionBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SuggestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SuggestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SuggestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SuggestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SuggestionDialog().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ballroomBtn;
    private javax.swing.JRadioButton billiardBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton candleBtn;
    private javax.swing.JRadioButton colMustardBtn;
    private javax.swing.JRadioButton conservatoryBtn;
    private javax.swing.JRadioButton diningBtn;
    private javax.swing.JRadioButton hallBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton kitchenBtn;
    private javax.swing.JRadioButton knifeBtn;
    private javax.swing.JRadioButton libraryBtn;
    private javax.swing.JRadioButton loungeBtn;
    private javax.swing.JButton makeSuggestionBtn;
    private javax.swing.JRadioButton mrGreenBtn;
    private javax.swing.JRadioButton mrsPeacockBtn;
    private javax.swing.JRadioButton mrsWhiteBtn;
    private javax.swing.JRadioButton pipeBtn;
    private javax.swing.JRadioButton profPlumBtn;
    private javax.swing.JRadioButton revolverBtn;
    private javax.swing.JRadioButton ropeBtn;
    private javax.swing.JRadioButton scarletBtn;
    private javax.swing.JRadioButton studyBtn;
    private javax.swing.JRadioButton wrenchBtn;
    // End of variables declaration//GEN-END:variables
}
